name: Delete Cloudflare Pages Preview Deployment

on:
  pull_request:
    types: [closed]

jobs:
  delete-cf-page-preview:
    name: Delete Cloudflare Pages Preview Deployment
    uses: ./.github/workflows/tmpl-cf-delete-preview.yaml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    with:
      REPOSITORY: ${{ github.repository }}
      REPOSITORY_NAME: 'ac-demo-blog'
      PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}